### ISSUE TITLE
Send `show create table\g` occur Panic

### ISSUE THREAD

**Issue by yuan-make** [cloudspannerecosystem/spanner-cli#67]
spanner-cli version : 0.6.3 
```
> show create table  tb1\g;

-panic: regexp: Compile(`(?i)^CREATE TABLE tb1\g`): error parsing regexp: invalid escape sequence: `\g`

goroutine 1 [running]:
regexp.MustCompile(0xc0000a6840, 0x17, 0x12)
	/usr/local/go/src/regexp/regexp.go:311 +0x152
main.(*ShowCreateTableStatement).Execute(0xc0005b4000, 0xc00045c8c0, 0x1d6d0a0, 0xc0005b4000, 0x0)
	/Users/x/go/pkg/mod/github.com/cloudspannerecosystem/spanner-cli@v0.6.3/statement.go:392 +0x315
main.(*Cli).RunInteractive(0xc00045c930, 0x0)
	/Users/x/go/pkg/mod/github.com/cloudspannerecosystem/spanner-cli@v0.6.3/cli.go:183 +0x4a2
```

**Comment by yfuruyama** [comment]
Hi, this issue was fixed in the PR: https://github.com/cloudspannerecosystem/spanner-cli/pull/65.

I just tagged `v0.6.4` for the latest code, so please reinstall the command and try it again.

**Comment by yfuruyama** [comment]
I believe this bug was fixed in https://github.com/cloudspannerecosystem/spanner-cli/pull/65. Please reopen this if the bug still happens on your side.
